spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      #metrics.enabled: true    
      routes:
      - id: account-service-mvc
        uri: http://localhost:8091
        predicates:
        - Path=/mvc/account/**
        filters:
        - StripPrefix=1
        - name: CircuitBreaker
          args:
            name: exampleCircuitBreaker
            fallbackUri: forward:/fallback/account
            
      - id: external-fallback
        uri: http://localhost:8091
        predicates:
        - Path=/fallback/account
        filters:
        - name: FallbackHeaders
          #args:
          #  executionExceptionTypeHeaderName: Test-Header

management:
  endpoints:
    web.exposure.include: '*'

            
